# fly.toml app configuration file generated for sms-router on 2023-05-21T21:40:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sms-router"
primary_region = "ams"
kill_signal = "SIGTERM"

[env]
  PHX_HOST = "sms.xetera.dev"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[metrics]
port = 4000
path = "/metrics"
